### ISSUE TITLE
Gene-Protein-Reaction associations in canonical format

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#209]
Probably won't get any support on this one, but here it goes anyway :)

GPR associations should be tested for biological meaning. The interpretation of boolean OR and AND operators as biological entities (isozymes and enzyme complexes) is only unambiguous if the boolean rule is encoded in a canonical format (disjunctive normal form, in this particular case).

This can be easily tested with the *is_dnf* function from sympy:

http://docs.sympy.org/latest/modules/logic.html#sympy.logic.boolalg.is_dnf

**Comment by cdiener** [comment]
Might also want to check for consistency. If all genes are switched off no reactions requiring an enzyme should be active and *vice versa*.

**Comment by cdanielmachado** [comment]
I think that would indicate a bug in the simulation method, not in the model...

**Comment by cdiener** [comment]
Yeah true, since `not` is not allowed...

**Comment by tpfau** [comment]
Both CNF and DNF do have biological meanings, with DNF being more obvious.
as @Midnighter pointed out, this is also linked to what I noticed in some models, where genes exist in GPR rules, but due to the GPR format cannot really have any influence. 
And this can be problematic, when trying to convert the formula into a dnf format, where those genes could simply be lost.

**Comment by cdanielmachado** [comment]
Can you give an example of a GPR in CNF and the respective biological meaning?

**Comment by cdanielmachado** [comment]
The reaction is catalyzed by complex `(A | B) & (C | D) `, which is not really a complex, but a rule that summarizes the formation of four possible complexes: AC, AD, BC, BD. These are the 4 isozymes that can catalyze the reaction.

I think DNF is more biologically meaningful, but as I said in the first post, I already know it will not be well accepted by most people. 

In fact, my actual proposal would be to get rid of boolean rules once and for all and replace them with true biological entities and true complex formation events with obvious biological meaning and interpretation, which I proposed for fbc2 but was never really accepted :)

**Comment by phantomas1234** [comment]
I am not sure I understand the problem (in terms of a model being actually problematic in terms of producing wrong results) with having a declarative rule like `(A | B) & (C | D)` describing four potential complexes?

**Comment by cdanielmachado** [comment]
It is not problematic if the GPR rule is used exclusively for a boolean simulation of the gene levels, i.e, simulating gene knockouts.

If you develop any other modeling approach that requires an interpretation of the biological meaning of the GPR association (e.g: enzyme production costs, transcriptomics data analysis, etc), then DNF has multiple advantages in my opinion. 

Anyway, I know this is a lost fight, so will just close the issue. :)

**Comment by tpfau** [comment]
@phantomas1234 I don't think there is a problem programmatically (because depending on the problem, you will have to use one format or the other anyways - as I mentioned in the link I posted).

@cdanielmachado I personally think that a better definition of GPR relationships would definitely be a good idea. 

But in the end, the format of the GPR rule doesn't matter, as we would need (imo) DP and PR rules, to avoid e.g. those problems I mentioned in #533 

And if you just want to map transcriptomics to map expression to genes to obtain maximal flux bounds, DNF can be quite misleading (as mentioned in the link).

**Comment by cdanielmachado** [comment]
That is strange, I used DNF in this work [1] for implementation of new methods for integration of transcriptomics data, and there was an obvious improvement in simulation accuracy in general. 

[1] https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005140

**Comment by tpfau** [comment]
@cdanielmachado 
Your approach is essentially enzyme capacity constraints, and yes, you will need DNF for that or rather you will need some way, to associate how your enzymes can be used. 
However, when e.g running the eflux concept (without complete conversion to enzyme coupling constraints) just trying to assign a maximal bound to reactions using the suggested min/sum (minimize for ands, sum for ors) DNF can give you odd situations (again have a look at the link). 

Just to clarify:
I personally think that the layout of the GPR rules (in their current boolean form) should not make any difference to an algorithm, since each algorithm makes certain assumptions about the format, and thus will need to reformulate the GPRs to fit its requirements or at least check, that they fit to it (or its bound to be doing something that its not supposed to do). 

And yes, I do think, that the GPR rule format we currently use needs to be updated in order to more properly represent what a GPR looks like. As we discussed about a year ago [here](https://github.com/opencobra/schema/issues/11)
