### ISSUE TITLE
[feature] check for growth on common media

### ISSUE THREAD

**Issue by cdiener** [opencobra/memote#211]
#### Problem description

Especially, for bacteria and simple eukaryotes it would be nice if one could check for growth on some of the common media LB, YPD, etc. Those could be passed as a list or just be a hard coded set of media that is checked. Would be hard to associate with exchange reactions but maybe one could use the annotations to maps those...

**Comment by Midnighter** [comment]
In #105 we are working on this (that PR has been much more extensive and drawn out than anticipated). You will be able to place tabular files that describe media and specify the media in growth, essentiality, and more tests.

We could offer certain standard media for download for the BiGG namespace but everyone has their own slight tweaks of what exactly is contained and each model has its specific exchanges. I would like to avoid that mess by relying on defined media rather than pre-defining our own.

**Comment by Midnighter** [comment]
Testing for growth is now possible when specifying the medium and expected outcomes.
