### ISSUE TITLE
Fix the stoichiometric consistency tests

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#378]
We accidentally fixed the nullspace function and it revealed a problem with the stoichiometric consistency methods by Gevorgyan et al.

Done: The methods should return the results expected from the paper.

**Comment by ChristianLieven** [comment]
@siddC how is this coming along?

**Comment by siddC** [comment]
So following what Niko said, I reverted the `check_stoichiometric_consistency` to only look at internal reactions and their metabolites and digging through the rest of the algorithm, I can't seem to find anything else in the code that looks like a bug. It seems to follow the algorithm laid out in the paper to a tee. I would have liked to discuss with @Midnighter on this to make sure the cobrapy/optlang part of the code is functioning as expected, but it seems fine to me. Which is why I'm so confused as to why the current tests with the fixed nullspace functions are failing a basic test model given in the paper.

**Comment by siddC** [comment]
Update: Looking over the ScumPy code, it seems as if the algorithm add the biomass reaction as a column to the S matrix and looks for a positive solution. I'll try and implement that in a test and see if that fixes our issues.

**Comment by Midnighter** [comment]
Hey Sidd, really sorry I'm never available to go through this issue with you. Are you able to run both the memote code and ScrumPy code step-by-step and side-by-side to identify where they diverge?

**Comment by siddC** [comment]
I'm not sure, as it doesn't seem like ScrumPy is supported on Macs yet, though the website did say support would be available by the end of 2017. It's why I ended up downloading the source files and looking over them instead, but the code in there does seem so old, I'm not even sure if it's py27. I'll try the linux installation and see if I can get it to work.
