### ISSUE TITLE
Correct format for annotations?

### ISSUE THREAD

**Issue by hvdinh16** [opencobra/memote#538]
Are there correct formats of keywords that allow memote to correctly predict the cross-references to the database? Memote test suite diagnosed my model's objects have annotations in general but cannot seem to further notice that I have specific database cross-references. The original model is in cobrapy and was written to SBML format via cobrapy's cobra.io.write_sbml_model. Example is provided below.

With the following annotation from my cobrapy model:
model.metabolites.atp_c.annotation
{u'ChEBI': u'30616',
 u'KEGG': u'C00002',
 u'MetaCyc': u'ATP',
 u'ModelSEED': u'cpd00002',
 u'PubChem': u'5957',
 u'fc_source': u'MetaCyc'}

I was able to make the following subsection of my XML file using cobra.io.write_sbml_model
 <species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_atp_c" name="ATP" metaid="M_atp_c" compartment="c" fbc:charge="-4" fbc:chemicalFormula="C10H12N5O13P3">
        <sbml:annotation xmlns:sbml="http://www.sbml.org/sbml/level3/version1/core">
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
            <rdf:Description rdf:about="#M_atp_c">
              <bqbiol:is xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/ChEBI/30616"/>
                  <rdf:li rdf:resource="http://identifiers.org/KEGG/C00002"/>
                  <rdf:li rdf:resource="http://identifiers.org/MetaCyc/ATP"/>
                  <rdf:li rdf:resource="http://identifiers.org/ModelSEED/cpd00002"/>
                  <rdf:li rdf:resource="http://identifiers.org/PubChem/5957"/>
                  <rdf:li rdf:resource="http://identifiers.org/fc_source/MetaCyc"/>
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </sbml:annotation>
      </species>

**Comment by Midnighter** [comment]
Yes, we try to stick to MIRIAM namespaces and use their patterns to validate identifiers. So, for example, for ChEBI you find that here https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000002 and thus it should be written for your example as
```python
'chebi': 'CHEBI:30616'
```

**Comment by jonovik** [comment]
Specifically, your examples could be:

```python
model.metabolites.atp_c.annotation = {
    "chebi": "CHEBI:30616",
    "kegg.compound": "C00002",
    "biocyc": "META:ATP",
    "seed.compound": "cpd00002",
    "pubchem.compound": "5957"
}
```

You could then generate working URLs by

```python
for namespace, identifier in model.metabolites.atp_c.annotation.items():
    print("http://identifiers.org/{}/{}".format(namespace, identifier))
```

http://identifiers.org/chebi/CHEBI:30616  
http://identifiers.org/kegg.compound/C00002  
http://identifiers.org/biocyc/META:ATP  
http://identifiers.org/seed.compound/cpd00002  
http://identifiers.org/pubchem.compound/5957  

There is also an http://identifiers.org/metacyc.compound, but its regular expression assumes all identifiers are `^CPD-\d{5}$`. You could [ask them](https://sourceforge.net/p/identifiers-org/_list/tickets) to accept ATP etc if you're not happy with the `biocyc/META:` solution.

The search field at http://identifiers.org usually helps in finding their "namespace" for a given ontology. ModelSEED was tricky because only "SEED" is mentioned. I googled [modelseed site:identifiers.org](https://www.google.com/search?q=modelseed+site%3Aidentifiers.org) and got lucky.

@Midnighter, I guess this issue can be closed.

**Comment by Midnighter** [comment]
Thank you for the elaborate examples @jonovik. This belongs more to model building and thus cobrapy but please let me know if the docs can be improved somewhere.

**Comment by hvdinh16** [comment]
Thanks for @Midnighter @jonovik replies. I think you should put this example or a more general guide on your documentations. I did not know about this specific MIRIAM namespace and a quick google search does not bring any relevant resources.
