### ISSUE TITLE
Total statistics graph unreadable (score per category, rotate axes labels)

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/memote#627]
The overview statistics plot (score per category) is unreadable (see screenshot). Axes labels must be rotated by 45 or 90 degrees for readability.

![sbo_example](https://user-images.githubusercontent.com/900538/54441004-13f5da80-473c-11e9-95cf-15b79604b85b.png)

Also it would be great to put the overall statistics back at the top of the report. Most of the time I just want to see the big number (and if it improved). This is the most important information and should be at the top at the report (like in earlier versions).

**Comment by ChristianLieven** [comment]
The plots ought to be fixed with #644.

We made a conscious decision to move the score and overviews to the bottom of the report in an effort to stop users from reducing models to `just` their score. We're hoping that scrolling through the report nudges users towards appreciating the nuances of model/reconstruction QC. Since the displays are still there It is merely a minor inconvenience, I believe, and this is outweighed by having consensus with co-authors who were adamant about removing the prominent display of the final score altogether.

**Comment by ChristianLieven** [comment]
Please reopen this issue if #644 hasn't addressed your concerns.

**Comment by matthiaskoenig** [comment]
@ChristianLieven Thanks for the fix and explanation. Issue is solved.
