### ISSUE TITLE
understanding bad quality results for models in online MEMOTE

### ISSUE THREAD

**Issue by shumantov** [opencobra/memote#726]
Hi,

I'm having some pretty bad results when using MEMOTE over the GSMM I have drafted via CarveMe, not sure why.

I used Cobrapy validator over the models and got the following output, which I guess means there are no errors:

(<Model bin_16 at 0x1ec5faf48e0>,
 {'SBML_FATAL': [],
  'SBML_ERROR': [],
  'SBML_SCHEMA_ERROR': [],
  'SBML_WARNING': [],
  'COBRA_FATAL': [],
  'COBRA_ERROR': [],
  'COBRA_WARNING': [],
  'COBRA_CHECK': []})

attached is the report results, hopefully the links works:

https://memote.io/report/8938c586-f1a0-403b-bf08-da16ed361fff

when run in MEMOTE both the 'stoichiometric consistency' and 'mass balance' give results of 0, wherein mass balance returns all purely metabolic reactions as unbalanced, and and stoichiometric consistency returns False. 

in the specific section, under SBML, the tests 'SBML Level and Version' and 'FBC enabled' returns null. 

I wonder whether I have did something wrong when building the models (when using carveme), or is it something in the input files that I have used (ordinary FASTA files), or maybe there is something I did not notice in the process of models drafting. any help regarding this issue would be much appreciated.

Thank you in advance!
Alon

**Comment by Midnighter** [comment]
That report seems to be missing? At least, I can't access it.

The issue seems to be that your model is not stoichiometrically consistent. Although carveme is generally quite good at this, it's not necessarily expected that a fresh draft model is consistent. So it would be up to your manual curation to fix this. Mass balance is probably lacking metabolite formulae, that's why all reactions are shown as unbalanced.

I haven't used carveme in a while now but I remember that it was using using SBML level 2 and not FBC which may also be why some of the information can't be accessed. Seeing the report or the model would allow me to help you further.

**Comment by shumantov** [comment]
Thank you for your response, and sorry for taking the time to answer!

First, is sharing the URL of the report given the right way to share it? any other way, without using Github?
Anyways, I'm giving another go.

https://memote.io/report/0ed5497d-e70e-4623-af85-0718423111df

This report was made now. Maybe the former has expired upon this issue opened. 

In the carveme script for creating the models, I have indicated FBC. like this:

```
data/bin/miniconda2/envs/carveme-v1.0/env_carveme.sh; carve /home/ARO.local/ginatta/Projects/metawarp/jobarray_test/inputs/bin.98.faa --fbc -o /home/ARO.local/ginatta/Projects/metawarp/jobarray_test/outputs/bin.98.xml
``` 

I'm constructing hundreds of models. Therefore, I would really like to avoid manual curation, which to be honest, I'm not sure how to approach, in small and large scales. Any ideas? 

In case manual curation is absolutely necessary - can you direct me to a resource regarding handling this issue?

Thanks again

**Comment by Midnighter** [comment]
This time I can see the report. I think there are quite a few things that you need to raise on the [carveme project](https://github.com/cdanielmachado/carveme/issues).

1. You can see in the test for unconserved metabolites that protons are not balanced. This is likely because carveme uses the BiGG universal model and some reactions are unbalanced in there. That is why the model is inconsistent.
2. Mass balance is a bit puzzling. Apparently molecular formulae are available on all metabolites but maybe they are simply wrong? This also prevents memote from checking the biomass reaction properly.
3. Annotations are completely missing because carveme writes that information in a non-standard way. The information is available on BiGG.
4. There is no enforced ATP maintenance flux. That means, some simulation results may be unrealistic.

I agree that manual curation for thousands of models is probably not feasible. Although it has been done for the AGORA collection. Some of these things can be fixed by improving carveme so that's your next best option, I think.

**Comment by shumantov** [comment]
Thank you for your inputs! 

Will raise on carveme. 

Cheers
