### ISSUE TITLE
getting the overall score of a benchmark suite test

### ISSUE THREAD

**Issue by shumantov** [opencobra/memote#737]
### Checklist

- [ X] I searched the [documentation](https://memote.readthedocs.io).
- [ X] I looked through [similar issues on GitHub](https://github.com/opencobra/memote/issues).
- [ X] I looked up "How to do ... in memote" on a search engine.

### Question

Hi,

I'm running multiple GSMMs (hundreds) in MEMOTE benchmark option, to check their quality, and I'm looking for a way to gather the overall score for each one of the models tested. I appended the test results to an empty file, but could not find that particular value. If it's there, I'm missing it.

Any help regarding this, or another approach I should take in order to asses the overall quality of the models via the benchmark option, would be much appreciated!

**Comment by Midnighter** [comment]
Hi @shumantov,

I realize that you asked a long time ago. So it's probably not relevant any longer. You could take a look at how we created the analysis for the publication. There we analyzed thousands of results files.

https://github.com/biosustain/memote-meta-study

You are correct that no total score is part of the result file, because the score can only be computed in combination with a particular set of weights for test results.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
